// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"example.com/grpc-todo/dao/impl"
	"example.com/grpc-todo/services"
)

// Injectors from wire.go:

func InitialiseTodoService() *crudTodo.TodoService {
	todoDao := impl.NewCrdbTodo()
	todoService := crudTodo.NewTodoService(todoDao)
	return todoService
}
